### ISSUE TITLE
Project name is not specified by default

### ISSUE THREAD

**Issue by haakonrob** [janjagusch/halite-battlestation#3]
After following the instructions after a clean install, I got the following traceback after running ``` poetry run python halite_battlestation/match_player.py```:

```
Traceback (most recent call last):
  File "halite_battlestation/match_player.py", line 179, in <module>
    subscribe()
  File "halite_battlestation/match_player.py", line 145, in subscribe
    def callback(message):
  File "/home/haakonrr/.cache/pypoetry/virtualenvs/halite-battlestation-khHttS4H-py3.8/lib/python3.8/site-packages/cloud_functions_utils/error_reporting.py", line 20, in __init__
    self._client = Client()
  File "/home/haakonrr/.cache/pypoetry/virtualenvs/halite-battlestation-khHttS4H-py3.8/lib/python3.8/site-packages/google/cloud/error_reporting/client.py", line 169, in __init__
    super(Client, self).__init__(
  File "/home/haakonrr/.cache/pypoetry/virtualenvs/halite-battlestation-khHttS4H-py3.8/lib/python3.8/site-packages/google/cloud/client.py", line 226, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/home/haakonrr/.cache/pypoetry/virtualenvs/halite-battlestation-khHttS4H-py3.8/lib/python3.8/site-packages/google/cloud/client.py", line 180, in __init__
    raise EnvironmentError(
OSError: Project was not passed and could not be determined from the environment.
```

After searching a bit I found https://github.com/GoogleCloudPlatform/python-docs-samples/issues/929, which pointed out that ```bigquery.Client()``` will raise an error unless a project name is set. This can be done in two ways:
+ Pass in a project name parameter when constructing bigquery clients:
   ```bigquery.Client(project="MyProject")```
+ Set a project name using ```gcloud config set project <name>```
   I ran the following: ```gcloud config set project halite```, which gave me the warning:
   ``` WARNING: You do not appear to have access to project [halite] or it does not exist.```
   Despite this, the issue was gone afterwards, and I could subscribe to match requests.

The first option seems like the easiest for the end-user,

**Comment by haakonrob** [comment]
I see that the actual name is kaggle-halite, gcloud doesn't emit any warnings now.

**Comment by haakonrob** [comment]
The traceback above shows that the error comes from the external package ```cloud_function_utils``` (confusingly, the same module lives inside the ```utils/ folder``` in this project :D). Instead of fixing that, it would be easier to just update the instructions, or set the config from within the script if possible. What do you think?

**Comment by janjagusch** [comment]
I added instructions for setting the project name to the docs, thanks for filing this issue!
